### PR TITLE
Clarify Installations instructions

### PR DESCRIPTION
**Pull request by Kapocsi**
Finding the FIRST' folder without knowing to look in the  `sdcard` folder is tedious as it is not located at the top level. 

CleanShot 2022-10-20 at 07 03 40

### CODE REVIEW

**Comment by Windwoes** [comment]
(Context: diff) this isn't really a Mac thing. If you use Android File transfer on Mac it will appear at the top level similar to how it appears in Windows explorer. The file manager pane in AS uses ADB as the backend which exposes the top level Linux file system of the Android device rather than just the USB storage. But, I suppose clarifying what to do for the AS file manager might be good.

**Comment by Kapocsi** [comment]
Ok, still, it would be helpful to clarify where that folder is; this language should be more explicit.

**Comment by Windwoes** [comment]
That wording still isn't quite right; Android File Transfer will have it a the top level, it's the file explorer in Android Studio that will have it at `/sdcard/FIRST`/

**Comment by Kapocsi** [comment]
Would this work?

**Pull request merged**
