### PR TITLE
Sm add fps param

### PR DESCRIPTION
**Pull request by smartynenko**
There is a bug in UvcApiCameraCharacteristics.getMaxFramesPerSecond which causes incorrect max FPS calculation for certain camera models (eg Microsoft LifeCam Show). Requesting to add helper method to allow fps override to work around the bug

### CODE REVIEW

**Comment by FROGbots-4634** [comment]
Are you certain it's actually a bug, and not the camera reporting incorrect information?

**Comment by smartynenko** [comment]
Good question. In either case the only way to make it work is to pass fps (=14) which is different than returned from UvcApiCameraCharacteristics.getMaxFramesPerSecond (=15, internally calculated value is 14.9999925 which is rounded to 15). Given the situation, it leaves two options

1) ignore the situation, which renders camera not supported with EasyOpenCv
2) accept the issue and provide work around

**Comment by FROGbots-4634** [comment]
I'm not opposed to adding a start streaming call with an fps parameter, but I'd like to do a bit of investigation on my end before doing so.

**Comment by smartynenko** [comment]
Sure, based on what I see, camera reports that it supports following modes:

    CameraMode(format=20 160x120 fps=14)
    CameraMode(format=20 800x600 fps=14)
    CameraMode(format=20 352x288 fps=14)
    CameraMode(format=20 176x144 fps=14)
    CameraMode(format=20 640x480 fps=14)
    CameraMode(format=20 320x240 fps=14)

This list seem to be ignored and system uses UvcFrameDesc.getFrameIntervals() method instead. This method internally calls native method nativeGetNullTerminatedList which reports that camera's frame rate is 666667 *100 ns. Later on this value gets processed in UvcApiCameraCharacteristics.getMaxFramesPerSecond and incorrectly rounded to 15, so the error is indeed in the SDK, but good luck waiting for FIRST to fix it :/

**Comment by FROGbots-4634** [comment]
Ok so, in the `CameraMode` constructor, it looks like we get "floor" rounding to 14FPS because of the integer division in the constructor (both `SECOND_IN_NANO` and `nsFrameDuration` are `long`s):

```java
this.fps = (int) (ElapsedTime.SECOND_IN_NANO / nsFrameDuration);
```

**Comment by FROGbots-4634** [comment]
Interesting that you say your webcam reported a min frame timing interval of `666667 * 100ns`. Here's what my laptop's UVC compatible camera supports at YUY2 320x240:

```
      VideoStreaming Interface Descriptor:
        bLength                            46
        bDescriptorType                    36
        bDescriptorSubtype                  5 (FRAME_UNCOMPRESSED)
        bFrameIndex                         3
        bmCapabilities                   0x00
          Still image unsupported
        wWidth                            320
        wHeight                           240
        dwMinBitRate                  6144000
        dwMaxBitRate                 36864000
        dwMaxVideoFrameBufferSize      153600
        dwDefaultFrameInterval         333333
        bFrameIntervalType                  5
        dwFrameInterval( 0)            333333
        dwFrameInterval( 1)            500000
        dwFrameInterval( 2)            666666
        dwFrameInterval( 3)           1000000
        dwFrameInterval( 4)           2000000
```

Notice that the supported timing intervals are:

```
 333333 * 100ns = 30.000030 FPS
 500000 * 100ns = 20.000000 FPS
 666666 * 100ns = 15.000015 FPS
1000000 * 100ns = 10.000000 FPS
2000000 * 100ns =  5.000000 FPS
```

Notice that for the 15FPS setting, it reports that the min supported timing interval is `666666 * 100ns`, but your camera reports `666667 * 100ns`. **This means that after conversion back to nanoseconds after rounding, the former will get an interval ever so slightly longer than the min supported, but the latter will get an interval ever so slighter shorter than min supported.**

Interesting....

**Comment by smartynenko** [comment]
I got some raw data, from usb controller, looks like camera is the culprit, below snapshot is for 800x600, but default frame interval is the same for all available formats

```
          ===>Video Streaming Uncompressed Frame Type Descriptor<===
bLength:                           0x1E
bDescriptorType:                   0x24
bDescriptorSubtype:                0x05
bFrameIndex:                       0x06
bmCapabilities:                    0x00
wWidth:                          0x0320 = 800
wHeight:                         0x0258 = 600
dwMinBitRate:                0x0BB80000
dwMaxBitRate:                0x0BB80000
dwMaxVideoFrameBufferSize:   0x003A9800
dwDefaultFrameInterval:      0x000A2C2B = 66.666700 mSec (15.00 Hz)
bFrameIntervalType:                0x01
===>Additional Discrete Frame Type Data
dwFrameInterval[1]:          0x000A2C2B = 66.666700 mSec (15.00 Hz)
```

**Comment by FROGbots-4634** [comment]
I pushed a commit to a new branch of ExtractedRC which might help to workaround the issue: https://github.com/OpenFTC/Extracted-RC/commit/83e0c239d0f348d18d4415e42ff2a9ac197f0cba. However, I can't really test if it works or not because I don't have a problematic webcam, haha. So, if you could test building [this branch](https://github.com/OpenFTC/Extracted-RC/compare/test_fix_uvc_fps_rounding_problems) of ExtractedRC, and see if the ConceptWebcam sample and **unmodified** EasyOpenCV work for you in what was the problematic configuration before, that would be great. Of course, running a modified SDK it not legal for competition, but if it works, then we can direct FIRST to the needed patch :)

**Comment by FROGbots-4634** [comment]
Oops, just realized I used the wrong variable in 2 places in that commit; I pushed another to fix that

**Comment by smartynenko** [comment]
Still failing with the same error

2020-10-09 14:29:39.250 1776-1911/com.qualcomm.ftcrobotcontroller E/CameraManager: camera reports error: CameraImpl(UsbResiliantWebcam(Webcam(1118:1833))): StreamingRequestNotSupported

**Comment by FROGbots-4634** [comment]
In the log output, did you see the message printed to log that I had added? If not it probably means the other code path was taken (I only modified one) and so I would need to modify the second path as well.

**Comment by FROGbots-4634** [comment]
Note: when I said "the message that I had added" I was referring to:

```cpp
LOGE("Camera does not support requested frame rate of %dFPS (interval %d*100ns) at resolution [%dx%d] format %d; choosing closest supported interval (%d*100ns)", fps, fpsConvertedTo100NsInterval, width, height, (int)cf, chosen);
```

**Comment by smartynenko** [comment]
I assume you refer to line # 450 in stream.cpp. The code is there, but control flow is not enter into that section when I ran it through debugger

**Comment by FROGbots-4634** [comment]
Ok. Can you check if the control flow goes through the [`else` block starting on line 466](https://github.com/OpenFTC/Extracted-RC/blob/4601c4d46f5f80ee31a1884adcf3bc0ab295823b/RobotCore/src/main/cpp/libuvc/src/stream.cpp#L466)?

**Comment by smartynenko** [comment]
It does not enter that section either

**Comment by FROGbots-4634** [comment]
Hrrrm. But *certainly* the flow enters the `uvc_get_stream_ctrl_format_size()` function, right? Because that's where the error in your log is originating from:

```
D/Uvc: [libuvc.h:147] [stream.cpp:470] originating err: -51(UVC_ERROR_INVALID_MODE)
D/Uvc: [stream.cpp:373] ...uvc_get_stream_ctrl_format_size() rc=-51
```

**Comment by smartynenko** [comment]
correct, it does go through this method

**Comment by FROGbots-4634** [comment]
But looking at the function, it seems very odd that it wouldn't go through either the `if` or `else` block for `if(pFrame->rgIntervals)`. Where *does* it go? Is it skipping over both because the `if (!rc)` check on line 385 failed??

**Comment by smartynenko** [comment]
It does enter into intoif (pFrame->rgIntervals) on line 405, it does not reach line 450, because chosen net gets assigned. Are you could you confirm if line 448 should be `if(chosen != 0)` and not `if(chosen == 0)`

**Comment by FROGbots-4634** [comment]
Ok, I just pushed another commit to that branch on ExtractedRC. Can you pull and give that a try? I verified that with my camera, if I request 30FPS, and force the exact search to fail, and force the closest match search to ignore the the 0th element (333333*100ns), then it correctly selects 24FPS as the closest supported match and successfully starts streaming.

**Comment by smartynenko** [comment]
this version worked with my camera as well. btw, do you have any plans to add 64-bit support?

**Comment by FROGbots-4634** [comment]
> this version worked with my camera as well

Great. Can you post what the output of that print statement was? I'd just like to confirm it said it couldn't do `666666` but chose the closest match at `666667`.

>  btw, do you have any plans to add 64-bit support?

For EasyOpenCV? Not at this time, no.

**Comment by smartynenko** [comment]
Here you go

```
2020-10-10 13:29:03.569 978-1262/com.qualcomm.ftcrobotcontroller D/Uvc: [libuvc/libuvc_internal.h:783] claimInterface(1) succeeded
2020-10-10 13:29:03.569 978-1262/com.qualcomm.ftcrobotcontroller D/Uvc: [libuvc/libuvc_internal.h:770] ...uvc_device_handle::claimInterface() rc=0
2020-10-10 13:29:03.569 978-1262/com.qualcomm.ftcrobotcontroller E/UvcStream: [stream.cpp:451] Camera does not support requested frame rate of 15FPS (interval 666666*100ns) at resolution [800x600] format 3; choosing closest supported interval (666667*100ns)
2020-10-10 13:29:03.569 978-1262/com.qualcomm.ftcrobotcontroller D/Uvc: [stream.cpp:162] uvc_query_stream_ctrl()...

```

**Comment by FROGbots-4634** [comment]
Perfect! Now just need to see if I can use my contacts to push FIRST to include this patch in the official SDK......

**Comment by smartynenko** [comment]
That would be the best outcome. Thank you!

**Comment by smartynenko** [comment]
I am getting some strange results with another external camera. Per specs, it supports 640x480@30FPS and appear to work fine when I call `startStreaming` with this parameters, however once streaming starts, actual FPS from  `((OpenCvWebcamImpl)webCam).getFps()` is ~3.5. Do you have any insights into what could be causing this behavior?

**Comment by FROGbots-4634** [comment]
Hmm, can you test the camera either on Linux with `guvcview` or on Windows with `OBS` and see what kind of frame rates you get there?

**Comment by smartynenko** [comment]
> Perfect! Now just need to see if I can use my contacts to push FIRST to include this patch in the official SDK......

Just wondering if there was any feedback from FIRST. thank you

**Comment by FROGbots-4634** [comment]
> Just wondering if there was any feedback from FIRST. thank you

They've informed me the patch will be included in the next release of the SDK.

**Comment by FROGbots-4634** [comment]
Closing this since SDK v6.1 is out and looks like this issue is fixed in that release: https://github.com/FIRST-Tech-Challenge/FtcRobotController#version-61-20201209-113742

**Pull request closed without merging**
